### ISSUE TITLE
you like to give me hopes on my Server

### ISSUE THREAD

**Issue by RandomGuyJunior** [Foghrye4/Iblis#10]
started Server. It worked.I Joined. New Error
java.lang.NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V
May i take a guess ? Gluttony has problems with applecore or other mods that affect hunger mechanic.
-same mods as before

This is the best i can offer you:
https://pastebin.com/e3SxJ1Gr

**Comment by Foghrye4** [comment]
Gluttony should have no problems with applecore at all, because Gluttony uses applecore if it is loaded.
This method is client side only. I missed that part. I hope 0.4.2 will work fine.

**Comment by RandomGuyJunior** [comment]
Thank you anyway. Your Mod is the most important one in my little collection. I couldnt bear to take it out.

**Comment by Foghrye4** [comment]
Thanks.

**Comment by RandomGuyJunior** [comment]
I cant make a Modpack about grinding without grinding.

**Comment by Foghrye4** [comment]
https://minecraft.curseforge.com/projects/iblis/files/2610371
Ok, it's available for download.

**Comment by RandomGuyJunior** [comment]
Thanks. If you ever need Help or Ideas you are free to ask.

**Comment by Foghrye4** [comment]
@RandomGuyJunior ideas? Sure. If you have suggestions considering Freetrading mod or Iblis mod or Labyrinth mod or Quicksave-Quickload mod go ahead and tell me.
