### ISSUE TITLE
Figured I'd let you know of a crash that occurs between two mods...

### ISSUE THREAD

**Issue by Shade-Jonezy** [Foghrye4/Iblis#12]
Your mod doesn't seem to like the Dissolution Mod.  I think it has to do with the creation of a zombie entity.  Keep in mind I said I think as even the crash log and Vanillafix Mod has no clue as to what causes the crash.  I had to remove Iblis to get Dissolution to stop crashing my modpack.  The crash happens during the load screen, not during gameplay.  I'm reporting this to the maker of Dissolution as well in case there is something they can do on their end as well.

**Comment by Foghrye4** [comment]
Last version of Dissolution cause crash without Iblis.

**Comment by Pyrofab** [comment]
Last version of Dissolution doesn't crash by itself. What version of Forge were you using ?

**Comment by Pyrofab** [comment]
Update: reproduced the crash with Iblis 0.4.3, Dissolution 0.1.4 and Forge 14.23.3.2669
Here's the crash and the log file:
https://gist.github.com/Pyrofab/b97db54de117fb686c3bc266ddd8ed4c
Interesting line:
`Registry EntityEntry: Override did not have an associated owner object. Name: dissolution:zombie_possessable Value: net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry@743e5472`
It would appear that this is my fault, however I would like to know if iblis does anything special to zombies that could cause this unintended behaviour

**Comment by Foghrye4** [comment]
I am registering extended class of vanilla zombie with registry entry "iblis:zombie". Yet I was able to reproduce crash with Iblis removed. It could be caused by one of my other mods. For example my other mod "Dungeon generator for Cubic Chunks" (labyrinth) also register entities. I will investigate case more throughtfully.

**Comment by Pyrofab** [comment]
Alright, that explains the aforementionned crash. And I am entirely responsible for it, sorry. 

Regarding yours, generally Dissolution's loading crashes (without other mods) are due to Forge being way outdated and unable to process contained dependencies, I think this is what you experienced.

**Comment by Foghrye4** [comment]
Renaming entity to "player_zombie" works fantastically good. Apparently Labyrinth also had a "Zombie" mob.

**Comment by Pyrofab** [comment]
Alright, I fixed it on my side. (version 0.1.5 will get the fix)

**Comment by Shade-Jonezy** [comment]
This allows the two to work in tandem well with no crash.
