### ISSUE TITLE
Crash on right clicking with book

### ISSUE THREAD

**Issue by Iashar** [Foghrye4/Iblis#14]
Takes a few minutes for me to start up my modded minecraft, so I'll add which book in a bit.
beginners manual to Chemistry volume 12
The 2 I used before it worked just fine, being beginners manual to medical aid vol 2 & 14
Iblis 0.4.4
forge 14.23.4.2759
MC 1.12.2
And of course, a crash log for your perusal.
https://pastebin.com/hmBSBQgb

**Comment by Foghrye4** [comment]
Thank you, fixed.
