### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by Josral** [Foghrye4/Iblis#15]
in Minecraft you can add two tools together to get a third with a bit better durability.  Such as make two axes, use each for a while, put both damaged axes in crafting table to get a third with a bit better durability than those two had left.  Iblis doesn't seem to cover this situation.  If it does then the pop-up info box for the tool doesn't reflect it.

**Comment by Foghrye4** [comment]
![untitled](https://user-images.githubusercontent.com/6910858/48431602-20b0f480-e783-11e8-8604-87c817ae09d2.png)
I have no idea what you talking about.

**Comment by Josral** [comment]
![firstaxe](https://user-images.githubusercontent.com/448109/48478597-c2abfd80-e7d2-11e8-86d8-ad33be57c325.png)
![secondaxe](https://user-images.githubusercontent.com/448109/48478631-d9525480-e7d2-11e8-9031-eddc0e15206b.png)
![thirdaxe](https://user-images.githubusercontent.com/448109/48478636-dd7e7200-e7d2-11e8-8adf-f664046b5190.png)

Ideally first and second axe should be damaged below 50%. Per the tooltips first and second are covered by iblis and are bad because my weapon skill is bad.  Third axe produced from first two per tooltip is a normal axe and not weakened by my lack of skill.
Adding two tools together is a vanilla feature.  Adding an axe at 45% and an axe at 35% produces an axe at better than 80% for example.  But the axe produced is not covered by iblis.

**Comment by Foghrye4** [comment]
Ow... in *crafting table*. Sorry, I did not paid attention on what I have read. I will try to fix this.

**Comment by Foghrye4** [comment]
Fixed. Thank you!

**Comment by Josral** [comment]
Your fix is not perfect.  It works for new axes and slightly used axes, but after a while it breaks and becomes a normal axe.

![onebrokeonenew](https://user-images.githubusercontent.com/448109/48966259-fa1d6580-ef9b-11e8-8163-675ccf8f9b9a.png)

![twobrokenaxes](https://user-images.githubusercontent.com/448109/48966263-06092780-ef9c-11e8-8324-58d6e7864364.png)

**Comment by Foghrye4** [comment]
Fixed again. (0.4.8)
