### ISSUE TITLE
Compatibility request for 'Realbench'

### ISSUE THREAD

**Issue by Josral** [Foghrye4/Iblis#16]
Compatibility request for 'Realbench'  [https://minecraft.curseforge.com/projects/realbench?gameCategorySlug=mc-mods&projectID=237414](url)  'Realbench' adds a feature to vanilla workbench to hold ingredients if one walks away without taking them.  'Iblis' is not compatible with that particular behavior, upon returning to the workbench, 'Iblis' does not see the tool, weapon, or armor that was left on the bench.  Currently, upon returning to the bench, one has to pick up one of the ingredients and set it back down for 'Iblis' to see it.  Otherwise, 'Iblis' works fine with 'Realbench' mod.

Edit: It is the 'practice' part of 'Iblis' that does not see the item upon return to the workbench.

**Comment by Foghrye4** [comment]
Done (0.4.11)
