### ISSUE TITLE
'Iblis' and 'From the Ground Up' do not get along

### ISSUE THREAD

**Issue by Josral** [Foghrye4/Iblis#17]
Decided to try another mod and world crashes when both 'Iblis' and 'From the Ground up' https://minecraft.curseforge.com/projects/from-the-ground-up?gameCategorySlug=mc-mods&projectID=250717[](url) are present.

[crash-2018-12-20_13.46.01-server.txt](https://github.com/Foghrye4/Iblis/files/2700132/crash-2018-12-20_13.46.01-server.txt)

I haven't tried the mod yet so don't know whether to request compatibility or not.  But do want to report the crash.

**Comment by Josral** [comment]
I have decided not to use 'From the Ground Up' after some play time with it.

**Comment by Foghrye4** [comment]
No-no, this is still an issue, even if you decide to drop 'From the Ground up' mod.

**Comment by Foghrye4** [comment]
Thanks, I think I fixed it. At least I was able to load world without crash.
