### ISSUE TITLE
New config option

### ISSUE THREAD

**Issue by JWTHDYTWA** [Foghrye4/Iblis#18]
Please make a config option for disabling custom 10+ heart overlay. For example certain mod (baubley heart canisters if i remember correctly) adds more aesthetical display of it, which i prefer.
![](https://i.imgur.com/CJeNFJY.gif)

**Comment by JWTHDYTWA** [comment]
And it wouldn't be excess to add configurable rates of skills gain.

**Comment by Foghrye4** [comment]
@Warrock3280 as I remember, hearts render is launched with low priority. If some other mod cancel event, Iblis won't render them. Check it with your preferred mod and tell me result (with screenshot if possible).

**Comment by JWTHDYTWA** [comment]
@Foghrye4 No, i've just checked and it overrides colored hearts overlay that was before. Idk, maybe it has lower priority. However, it would be better to add config option for disabling it manually.

**Comment by Foghrye4** [comment]
@Warrock3280 could you give me a link to curseforge page of  a "baubley heart canisters" or whatever it named?

**Comment by JWTHDYTWA** [comment]
[Here is it.](https://minecraft.curseforge.com/projects/baubley-heart-canisters) But i'm not completely sure it's it. It may be Quark or even some FTB mod. I'll look into it once more.

**Comment by Foghrye4** [comment]
Done.
