### ISSUE TITLE
Crashes with crossbow and unable to use shotgun on server.

### ISSUE THREAD

**Issue by rfwainug** [Foghrye4/Iblis#19]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
  HCASM (HammerCore-1.12.2-2.0.4.1.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/5/19 1:42 AM
Description: Ticking entity

java.lang.NoSuchMethodError: net/minecraft/util/math/AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V (loaded from jar:file:/home/minecraft/servers/mine242876/minecraft_server.1.12.2.jar!/bhb.class by net.minecraft.launchwrapper.LaunchClassLoader@46dfc932) called from class iblis.entity.EntityCrossbowBolt (loaded from jar:file:/home/minecraft/servers/mine242876/./mods/1.12.2/iblis-0.5.2.jar!/iblis/entity/EntityCrossbowBolt.class by net.minecraft.launchwrapper.LaunchClassLoader@46dfc932).
	at iblis.entity.EntityCrossbowBolt.func_184551_a(EntityCrossbowBolt.java:112)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:248)
	at iblis.entity.EntityCrossbowBolt.func_70071_h_(EntityCrossbowBolt.java:78)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:813)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at iblis.entity.EntityCrossbowBolt.func_184551_a(EntityCrossbowBolt.java:112)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:248)
	at iblis.entity.EntityCrossbowBolt.func_70071_h_(EntityCrossbowBolt.java:78)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: iblis:crossbow_bolt (iblis.entity.EntityCrossbowBolt)
	Entity ID: 7
	Entity Name: entity.CrossbowBolt.name
	Entity's Exact location: -10.27, 37.38, 315.60
	Entity's Block location: World: (-11,37,315), Chunk: (at 5,2,11 in -1,19; contains blocks -16,0,304 to -1,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.32, -0.64, 7.99
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: map
	All players: 1 total; [EntityPlayerMP['starwolf62'/192, l='map', x=-10.23, y=36.00, z=314.62]]
	Chunk stats: ServerChunkCache: 778 Drop: 0
	Level seed: 1652597312920824284
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (176,64,256), Chunk: (at 0,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2818276 game time, 2875495 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 130551 (now: false), thunder time: 18894 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:813)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.120-xxxx-std-ipv6-64-hz1000
	Java Version: 1.8.0_192, Eclipse OpenJ9
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Linux amd64-64-Bit Compressed References 20181107_95 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dcd
OMR      - ea548a66
JCL      - b5a3affe73 based on jdk8u192-b12), Eclipse OpenJ9
	Memory: 209306776 bytes (199 MB) / 674234368 bytes (643 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -Xoptionsfile=/home/minecraft/java/1.8.0_192_openj9-0.11.0/jre/lib/amd64/compressedrefs/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse7b_29 -XX:+IdleTuningGcOnIdle -Xdump:none -Xquickstart -Xtune:virtualized -Xmx4096M -Xms512M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2810 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                   | Version                | Source                                                   | Signature                                |
	|:------ |:------------------------------------ |:---------------------- |:-------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                            | 1.12.2                 | minecraft.jar                                            | None                                     |
	| LCHIJA | mcp                                  | 9.42                   | minecraft.jar                                            | None                                     |
	| LCHIJA | FML                                  | 8.0.99.99              | forge-1.12.2-14.23.5.2810.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                | 14.23.5.2810           | forge-1.12.2-14.23.5.2810.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | passableleavescore                   | 1.0.0                  | minecraft.jar                                            | None                                     |
	| LCHIJA | badmobs                              | 1.1.36                 | BadMobs-1.12.2-1.1.36.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | baubles                              | 1.5.2                  | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LCHIJA | bettercombatmod                      | 1.5.6                  | BetterCombat-1.12.2-1.5.6.jar                            | None                                     |
	| LCHIJA | bionisation3                         | 1.0.6                  | Bionisation3-1.12.2-1.0.6.jar                            | None                                     |
	| LCHIJA | crafttweaker                         | 4.1.14                 | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | mantle                               | 1.12-1.3.3.39          | Mantle-1.12-1.3.3.39.jar                                 | None                                     |
	| LCHIJA | jei                                  | 4.14.4.261             | jei_1.12.2-4.14.4.261.jar                                | None                                     |
	| LCHIJA | tconstruct                           | 1.12.2-2.12.0.115      | TConstruct-1.12.2-2.12.0.115.jar                         | None                                     |
	| LCHIJA | conarm                               | 1.2.3                  | conarm-1.12.2-1.2.3.jar                                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cosmeticarmorreworked                | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | crafttweakerjei                      | 2.0.2                  | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | cyberware                            | 0.2.10.15              | cyberware-1.12.2-0.2.10.15.jar                           | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJA | cyclopscore                          | 1.0.1                  | CyclopsCore-1.12.2-1.0.1.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | dawnoftime                           | 0.1                    | dawnoftime-alpha-1.0.0.jar                               | None                                     |
	| LCHIJA | dynamicstealth                       | 1.12.2.044             | DynamicStealth-1.12.2.044.jar                            | None                                     |
	| LCHIJA | enchantability                       | 0.0.1                  | enchantability-1.0.jar                                   | None                                     |
	| LCHIJA | epicsiegemod                         | 13.163                 | EpicSiegeMod-13.163.jar                                  | None                                     |
	| LCHIJA | fastleafdecay                        | v14                    | FastLeafDecay-v14.jar                                    | None                                     |
	| LCHIJA | ftblib                               | 5.4.0.73               | FTBLib-5.4.0.73.jar                                      | None                                     |
	| LCHIJA | ftbutilities                         | 5.3.0.68               | FTBUtilities-5.3.0.68.jar                                | None                                     |
	| LCHIJA | gravestone                           | 1.10.2                 | gravestone-1.10.2.jar                                    | None                                     |
	| LCHIJA | hammercore                           | 2.0.4.1                | HammerCore-1.12.2-2.0.4.1.jar                            | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | lucraftcore                          | 1.12.2-2.3.4           | LucraftCore-1.12.2-2.3.4.jar                             | None                                     |
	| LCHIJA | heroesexpansion                      | 1.12.2-1.2.3           | HeroesExpansion-1.12.2-1.2.3.jar                         | None                                     |
	| LCHIJA | howlingmoon                          | 0.9                    | howlingmooncustom.jar                                    | None                                     |
	| LCHIJA | iblis                                | 0.5.2                  | iblis-0.5.2.jar                                          | None                                     |
	| LCHIJA | iblis_headshots                      | 1.2.0                  | iblis-0.5.2.jar                                          | None                                     |
	| LCHIJA | improvedbackpacks                    | 1.12.2-1.4.0.0         | ImprovedBackpacks-1.12.2-1.4.0.0.jar                     | None                                     |
	| LCHIJA | infernalmobs                         | 1.7.5                  | InfernalMobs-1.12.2.jar                                  | None                                     |
	| LCHIJA | jepb                                 | 1.2.1                  | jepb-1.12-1.2.1.jar                                      | None                                     |
	| LCHIJA | livingenchantment                    | 3.1.5                  | living_enchantment-3.1.5.jar                             | None                                     |
	| LCHIJA | locks                                | 2.2                    | Locks-2.2.jar                                            | None                                     |
	| LCHIJA | radixcore                            | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar                     | None                                     |
	| LCHIJA | mca                                  | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                           | None                                     |
	| LCHIJA | metallurgy                           | 0.0.5                  | Metallurgy-4-Reforged-0.0.5.jar                          | None                                     |
	| LCHIJA | targeting_api                        | 0.12                   | targeting_api-0.12.jar                                   | None                                     |
	| LCHIJA | mkultra                              | 0.80                   | MKUltra-0.80.jar                                         | None                                     |
	| LCHIJA | moreplayermodels                     | 1.12.2                 | MorePlayerModels_1.12.2(18jan18).jar                     | None                                     |
	| LCHIJA | collapsingcolumns                    | @VERSION@              | nonerdpoles-1.12.2-2.0.4.jar                             | None                                     |
	| LCHIJA | sandro                               | 1.2d                   | Redstone+++ver1.2d.jar                                   | None                                     |
	| LCHIJA | redstoneplusplus                     | 1.2d                   | Redstone+++ver1.2d.jar                                   | None                                     |
	| LCHIJA | redstonepaste                        | 1.7.5                  | redstonepaste-mc1.12-1.7.5.jar                           | None                                     |
	| LCHIJA | rewired                              | 1.12.2                 | ReWIRED-1.0.4.jar                                        | None                                     |
	| LCHIJA | stg                                  | 1.12.2-1.2.3           | stg-1.12.2-1.2.3.jar                                     | None                                     |
	| LCHIJA | tails                                | 1.12-1.10.0            | Tails-1.12-1.10.0.jar                                    | None                                     |
	| LCHIJA | tinkersarsenal                       | 0.5                    | tinkersarsenal-0.5.jar                                   | None                                     |
	| LCHIJA | unhealthydying                       | 1.2.2.1                | Unhealthy-Dying-1.2.2.1.jar                              | None                                     |
	| LCHIJA | vampire                              | 0.0.2B                 | vampire-0.0.2B.jar                                       | None                                     |
	| LCHIJA | vampirism                            | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJA | teamlapen-lib                        | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJA | vampirism_integrations               | vampirism_integrations | VampirismIntegrations-1.12.2-1.1.0-alpha+12-09-22-44.jar | None                                     |
	| LCHIJA | walljump                             | 1.12.2-1.2.1           | walljump-1.12.2-1.2.1.jar                                | None                                     |
	| LCHIJA | passableleaves                       | 2.0.0                  | PassableLeaves-1.12.2-2.0.0.jar                          | None                                     |

	Loaded coremods (and transformers): 
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
HCASM (HammerCore-1.12.2-2.0.4.1.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 1844 names; 588 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUKCmNsaWVudCB7CiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdCiAgICBCOiJDdXN0b20gRW5jaGFudG1lbnQgQ29sb3JzIGZvciBWYW5pbGxhIEl0ZW1zIj10cnVlCgogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8KICAgICMgVGhpcyBmZWF0dXJlIGRvZXNuJ3Qgd29yayBvbiBhbGwgY2xpZW50cywgeW91IGFyZSBnb2luZyB0byBnZXQgYSBtZXNzYWdlIGluIGNoYXQgaWYgaXQgd2FzIHN1Y2Nlc3NmdWwvdW5zdWNjZXNzZnVsIFtkZWZhdWx0OiB0cnVlXQogICAgQjoiTEFOIFVQblAiPXRydWUKCiAgICAjIFJlcGxhY2UgdmFuaWxsYSBmdXJuYWNlIGFuZCBicmV3aW5nIHN0YW5kIHByb2dyZXNzIGJhcnMgdG8gdXNlIHNtb290aCByZW5kZXJpbmc/IFtkZWZhdWx0OiB0cnVlXQogICAgQjoiU21vb3RoIFZhbmlsbGEgR3VpcyI9dHJ1ZQp9CgoKaXdyZW5jaCB7CiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpCiAgICBTOkdyZWVuPTIyRkYyMgoKICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpCiAgICBTOlJlZD1GRjIyMjIKfQoKCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgewogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgZm9yY2Utc3Bhd24gRW5kZXIgRHJhZ29uIEVnZyBvbiBFbmRlciBEcmFnb24gZGVhdGg/IFtkZWZhdWx0OiB0cnVlXQogICAgQjoiQWx3YXlzIFNwYXduIERyYWdvbiBFZ2ciPXRydWUKfQoKCg==
Pastebin Connection: Okay.
Dependent Mods: None.

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['starwolf62'/192, l='map', x=-10.23, y=36.00, z=314.62]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by rfwainug** [comment]
I can only tell you about the shotgun since it doesn't crash, but oddly it gives the player the ability to hit blocks several meters away instead of firing with LMB? You can't mine, but you can tap a block very far away.

**Comment by Foghrye4** [comment]
Thank you! Fixed.
