### ISSUE TITLE
Problem with shooting another player with shotgun.

### ISSUE THREAD

**Issue by rfwainug** [Foghrye4/Iblis#20]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/6/19 2:28 AM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at iblis.item.ItemShotgun.shoot(ItemShotgun.java:80)
	at iblis.item.ItemFirearmsBase.onShoot(ItemFirearmsBase.java:109)
	at iblis.item.ItemFirearmsBase.func_77644_a(ItemFirearmsBase.java:67)
	at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:366)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1421)
	at bettercombat.mod.client.handler.EventHandlersClient.onMouseLeftClick(EventHandlersClient.java:100)
	at bettercombat.mod.client.handler.EventHandlersClient.onMouseEvent(EventHandlersClient.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_516_EventHandlersClient_onMouseEvent_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:273)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2275)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1800)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at iblis.item.ItemShotgun.shoot(ItemShotgun.java:80)
	at iblis.item.ItemFirearmsBase.onShoot(ItemFirearmsBase.java:109)
	at iblis.item.ItemFirearmsBase.func_77644_a(ItemFirearmsBase.java:67)
	at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:366)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1421)
	at bettercombat.mod.client.handler.EventHandlersClient.onMouseLeftClick(EventHandlersClient.java:100)
	at bettercombat.mod.client.handler.EventHandlersClient.onMouseEvent(EventHandlersClient.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_516_EventHandlersClient_onMouseEvent_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:273)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2275)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['starwolf62'/151, l='MpServer', x=297.75, y=63.00, z=283.04], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=296.30, y=62.00, z=285.70]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (176,64,256), Chunk: (at 0,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4155884 game time, 749409 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 102 total; [EntityPlayerSP['starwolf62'/151, l='MpServer', x=297.75, y=63.00, z=283.04], EntityItem['item.item.batwing'/12291, l='MpServer', x=-114.66, y=28.00, z=332.35], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=302.81, y=52.00, z=282.53], EntityItem['item.item.egg'/26884, l='MpServer', x=356.71, y=66.00, z=224.38], EntityItem['item.item.arrow'/26639, l='MpServer', x=292.07, y=20.00, z=219.59], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=305.66, y=52.00, z=284.64], EntityItem['item.item.arrow'/26640, l='MpServer', x=293.01, y=20.00, z=220.78], EntityItem['item.item.bone'/26641, l='MpServer', x=293.32, y=20.00, z=219.75], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=293.42, y=65.17, z=242.70], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=305.75, y=52.00, z=283.34], EntityXPOrb['Experience Orb'/27697, l='MpServer', x=306.13, y=63.00, z=282.74], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=309.37, y=50.52, z=285.21], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=303.73, y=52.00, z=281.67], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=305.30, y=52.00, z=283.11], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=298.62, y=54.11, z=276.30], EntityItem['item.item.dyePowder.black'/25399, l='MpServer', x=247.13, y=32.00, z=264.45], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=299.13, y=56.23, z=276.30], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.50, y=58.06, z=276.30], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.90, y=59.02, z=276.30], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=306.81, y=52.00, z=282.86], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=309.72, y=50.52, z=285.70], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=306.42, y=52.00, z=282.99], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=296.30, y=62.00, z=285.70], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=311.07, y=37.05, z=285.08], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=309.19, y=35.05, z=283.17], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=309.54, y=52.00, z=281.28], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=307.72, y=52.00, z=280.85], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=307.57, y=52.00, z=282.49], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=308.18, y=52.00, z=284.91], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.69, y=63.00, z=287.02], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=310.03, y=49.20, z=284.55], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.69, y=63.00, z=287.02], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=296.30, y=62.00, z=285.70], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.69, y=63.00, z=287.02], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=264.36, y=59.12, z=264.86], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.69, y=63.00, z=287.02], EntityItem['item.item.spiderleg'/26710, l='MpServer', x=282.88, y=28.00, z=323.75], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.69, y=63.00, z=287.02], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=306.13, y=52.00, z=283.17], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=308.18, y=52.00, z=284.91], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=305.53, y=52.00, z=283.04], EntityItem['item.item.dyePowder.black'/25947, l='MpServer', x=248.76, y=33.00, z=263.60], EntityItem['item.item.string'/26715, l='MpServer', x=280.53, y=27.00, z=325.02], EntityItem['item.tile.gravel'/26717, l='MpServer', x=279.13, y=28.00, z=326.08], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=305.13, y=52.00, z=283.32], EntityItem['item.tile.gravel'/26719, l='MpServer', x=280.09, y=28.00, z=324.90], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=306.55, y=52.00, z=283.10], EntityItem['item.tile.gravel'/26720, l='MpServer', x=282.06, y=28.00, z=324.28], EntityItem['item.item.flint'/26721, l='MpServer', x=278.13, y=29.00, z=324.50], EntityItem['item.item.chestplateGold'/27745, l='MpServer', x=238.03, y=25.77, z=233.28], EntityItem['item.tile.gravel'/26722, l='MpServer', x=281.27, y=27.00, z=323.14], EntityItem['item.tile.stonebrick'/26724, l='MpServer', x=279.13, y=28.00, z=323.14], EntityItem['item.tile.oreIron'/26725, l='MpServer', x=287.42, y=33.00, z=324.10], EntityItem['item.tile.gravel'/26726, l='MpServer', x=281.88, y=28.00, z=326.04], EntityItem['item.tile.gravel'/26727, l='MpServer', x=277.13, y=30.00, z=326.52], EntityItem['item.tile.stonebrick'/26728, l='MpServer', x=280.10, y=29.00, z=326.73], EntityItem['item.item.flint'/26729, l='MpServer', x=281.77, y=28.00, z=324.01], EntityItem['item.tile.stonebrick'/26731, l='MpServer', x=282.15, y=28.00, z=324.74], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=270.55, y=62.70, z=255.89], EntityItem['item.item.rottenFlesh'/26733, l='MpServer', x=310.17, y=20.00, z=264.32], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=308.18, y=52.00, z=284.91], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=308.34, y=52.00, z=285.02], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=303.67, y=52.00, z=283.64], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.68, y=57.50, z=276.59], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.83, y=59.05, z=276.30], EntityXPOrb['Experience Orb'/26485, l='MpServer', x=268.73, y=56.00, z=252.78], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=307.56, y=52.00, z=284.61], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=301.44, y=59.00, z=276.31], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=269.77, y=62.41, z=254.85], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=295.37, y=62.01, z=284.41], EntityItem['item.item.sulphur'/27029, l='MpServer', x=284.01, y=32.00, z=323.32], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=301.71, y=52.00, z=280.50], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=299.07, y=54.05, z=277.53], EntityItem['item.item.arrow'/25246, l='MpServer', x=313.37, y=18.00, z=274.77], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.70, y=58.00, z=276.31], EntityItem['item.item.bone'/25247, l='MpServer', x=312.72, y=18.00, z=274.33], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=296.30, y=62.00, z=285.70], EntityItem['item.item.cyberware.brain_upgrades.matrix'/25248, l='MpServer', x=313.00, y=18.00, z=274.12], EntityItem['item.item.coal'/25249, l='MpServer', x=313.83, y=18.00, z=273.12], EntityItem['item.item.bone'/25250, l='MpServer', x=313.88, y=18.00, z=273.22], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=300.11, y=57.75, z=277.85], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=302.99, y=52.00, z=281.43], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=302.63, y=52.00, z=283.72], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=301.40, y=59.00, z=276.30], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=303.70, y=59.00, z=276.47], EntityItem['item.item.bone'/26291, l='MpServer', x=332.75, y=39.00, z=226.24], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=306.68, y=52.10, z=285.17], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=303.70, y=59.00, z=276.47], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=306.75, y=52.00, z=282.59], EntityItem['item.tile.dirt.default'/26039, l='MpServer', x=293.08, y=61.00, z=241.88], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=305.61, y=52.00, z=282.38], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=304.71, y=60.87, z=276.50], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=305.61, y=52.00, z=282.38], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=303.83, y=52.00, z=280.27], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=305.57, y=52.00, z=280.50], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=305.55, y=61.14, z=276.70], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=301.63, y=63.00, z=288.01], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=301.63, y=63.00, z=288.02], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=306.88, y=52.00, z=283.81], EntityItem['item.item.batwing'/27094, l='MpServer', x=325.39, y=22.00, z=278.66], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=301.63, y=63.00, z=288.02], EntityOtherPlayerMP['Harlaus'/12863, l='MpServer', x=301.27, y=63.00, z=286.27]]
	Retry entities: 14 total; [EntityItem['item.item.batwing'/12291, l='MpServer', x=-114.66, y=28.00, z=332.35], EntityItem['item.item.batwing'/12549, l='MpServer', x=-106.88, y=32.00, z=228.58], EntityItem['item.item.spiderleg'/12839, l='MpServer', x=-39.53, y=70.00, z=270.95], EntityItem['item.item.arrow'/12426, l='MpServer', x=-96.68, y=31.00, z=322.26], EntityItem['item.item.bone'/12427, l='MpServer', x=-97.94, y=18.00, z=321.26], EntityItem['item.tile.stonebrick'/11471, l='MpServer', x=-101.45, y=48.00, z=225.88], EntityItem['item.tile.stonebrick'/11472, l='MpServer', x=-99.45, y=48.00, z=224.79], EntityItem['item.item.batwing'/12528, l='MpServer', x=-67.42, y=17.00, z=231.88], EntityItem['item.tile.stonebrick'/11473, l='MpServer', x=-102.26, y=48.00, z=223.90], EntityItem['item.item.rottenFlesh'/12372, l='MpServer', x=-108.56, y=30.00, z=328.78], EntityMinecartChest['Minecart with Chest'/152, l='MpServer', x=-91.50, y=61.06, z=278.50], EntityItem['item.item.dyePowder.black'/11864, l='MpServer', x=-60.02, y=62.00, z=331.49], EntityItem['item.item.string'/12762, l='MpServer', x=-103.80, y=34.00, z=224.95], EntityItem['item.tile.dirt.default'/12797, l='MpServer', x=-129.13, y=64.00, z=224.13]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2498708264 bytes (2382 MB) / 5268045824 bytes (5024 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2784 66 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                   | Version                | Source                                                   | Signature                                |
	|:------ |:------------------------------------ |:---------------------- |:-------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                            | 1.12.2                 | minecraft.jar                                            | None                                     |
	| LCHIJA | mcp                                  | 9.42                   | minecraft.jar                                            | None                                     |
	| LCHIJA | FML                                  | 8.0.99.99              | forge-1.12.2-14.23.5.2784.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                | 14.23.5.2784           | forge-1.12.2-14.23.5.2784.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | passableleavescore                   | 1.0.0                  | minecraft.jar                                            | None                                     |
	| LCHIJA | armorsouls                           | 1.0.1                  | Armor+Souls+1.0.1+Forge.jar                              | None                                     |
	| LCHIJA | badmobs                              | 1.1.36                 | BadMobs-1.12.2-1.1.36.jar                                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | baubles                              | 1.5.2                  | Baubles-1.12-1.5.2.jar                                   | None                                     |
	| LCHIJA | bettercombatmod                      | 1.5.6                  | BetterCombat-1.12.2-1.5.6.jar                            | None                                     |
	| LCHIJA | bionisation3                         | 1.0.6                  | Bionisation3-1.12.2-1.0.6.jar                            | None                                     |
	| LCHIJA | crafttweaker                         | 4.1.14                 | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | mantle                               | 1.12-1.3.3.39          | Mantle-1.12-1.3.3.39.jar                                 | None                                     |
	| LCHIJA | jei                                  | 4.14.4.261             | jei_1.12.2-4.14.4.261.jar                                | None                                     |
	| LCHIJA | tconstruct                           | 1.12.2-2.12.0.115      | TConstruct-1.12.2-2.12.0.115.jar                         | None                                     |
	| LCHIJA | conarm                               | 1.2.3                  | conarm-1.12.2-1.2.3.jar                                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cosmeticarmorreworked                | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | toughasnails                         | 3.1.0.139              | ToughAsNails-1.12.2-3.1.0.139-universal.jar              | None                                     |
	| LCHIJA | corpsecomplex                        | 1.0.3                  | corpsecomplex-1.12.2-1.0.3.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4              | CosmeticArmorReworked-1.12.2-v4.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | ctgui                                | 1.0.0                  | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | crafttweakerjei                      | 2.0.2                  | CraftTweaker2-1.12-4.1.14.jar                            | None                                     |
	| LCHIJA | modcurrency                          | 1.12-1.3.6             | Currency-1.12.0-1.3.6.jar                                | None                                     |
	| LCHIJA | cyberware                            | 0.2.10.15              | cyberware-1.12.2-0.2.10.15.jar                           | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJA | cyclopscore                          | 1.0.1                  | CyclopsCore-1.12.2-1.0.1.jar                             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | dawnoftime                           | 0.1                    | dawnoftime-alpha-1.0.0.jar                               | None                                     |
	| LCHIJA | dynamicstealth                       | 1.12.2.044             | DynamicStealth-1.12.2.044.jar                            | None                                     |
	| LCHIJA | enchantability                       | 0.0.1                  | enchantability-1.0.jar                                   | None                                     |
	| LCHIJA | epicsiegemod                         | 13.163                 | EpicSiegeMod-13.163.jar                                  | None                                     |
	| LCHIJA | fastleafdecay                        | v14                    | FastLeafDecay-v14.jar                                    | None                                     |
	| LCHIJA | ftblib                               | 5.4.0.73               | FTBLib-5.4.0.73.jar                                      | None                                     |
	| LCHIJA | ftbutilities                         | 5.3.0.68               | FTBUtilities-5.3.0.68.jar                                | None                                     |
	| LCHIJA | gravestone                           | 1.10.2                 | gravestone-1.10.2.jar                                    | None                                     |
	| LCHIJA | lucraftcore                          | 1.12.2-2.3.4           | LucraftCore-1.12.2-2.3.4.jar                             | None                                     |
	| LCHIJA | heroesexpansion                      | 1.12.2-1.2.3           | HeroesExpansion-1.12.2-1.2.3.jar                         | None                                     |
	| LCHIJA | howlingmoon                          | 0.9                    | howlingmooncustom.jar                                    | None                                     |
	| LCHIJA | iblis                                | 0.5.3                  | iblis-0.5.3.jar                                          | None                                     |
	| LCHIJA | iblis_headshots                      | 1.2.0                  | iblis-0.5.3.jar                                          | None                                     |
	| LCHIJA | improvedbackpacks                    | 1.12.2-1.4.0.0         | ImprovedBackpacks-1.12.2-1.4.0.0.jar                     | None                                     |
	| LCHIJA | infernalmobs                         | 1.7.5                  | InfernalMobs-1.12.2.jar                                  | None                                     |
	| LCHIJA | jepb                                 | 1.2.1                  | jepb-1.12-1.2.1.jar                                      | None                                     |
	| LCHIJA | livingenchantment                    | 3.1.5                  | living_enchantment-3.1.5.jar                             | None                                     |
	| LCHIJA | locks                                | 2.2                    | Locks-2.2.jar                                            | None                                     |
	| LCHIJA | radixcore                            | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar                     | None                                     |
	| LCHIJA | mca                                  | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                           | None                                     |
	| LCHIJA | metallurgy                           | 0.0.5                  | Metallurgy-4-Reforged-0.0.5.jar                          | None                                     |
	| LCHIJA | targeting_api                        | 0.12                   | targeting_api-0.12.jar                                   | None                                     |
	| LCHIJA | mkultra                              | 0.80                   | MKUltra-0.80.jar                                         | None                                     |
	| LCHIJA | moreplayermodels                     | 1.12.2                 | MorePlayerModels_1.12.2(18jan18).jar                     | None                                     |
	| LCHIJA | morpheus                             | 1.12-3.3.2             | Morpheus-1.12-3.3.2.jar                                  | None                                     |
	| LCHIJA | collapsingcolumns                    | @VERSION@              | nonerdpoles-1.12.2-2.0.4.jar                             | None                                     |
	| LCHIJA | sandro                               | 1.2d                   | Redstone+++ver1.2d.jar                                   | None                                     |
	| LCHIJA | redstoneplusplus                     | 1.2d                   | Redstone+++ver1.2d.jar                                   | None                                     |
	| LCHIJA | redstonepaste                        | 1.7.5                  | redstonepaste-mc1.12-1.7.5.jar                           | None                                     |
	| LCHIJA | rewired                              | 1.12.2                 | ReWIRED-1.0.4.jar                                        | None                                     |
	| LCHIJA | sereneseasons                        | 1.2.15                 | SereneSeasons-1.12.2-1.2.15-universal.jar                | None                                     |
	| LCHIJA | stg                                  | 1.12.2-1.2.3           | stg-1.12.2-1.2.3.jar                                     | None                                     |
	| LCHIJA | tails                                | 1.12-1.10.0            | Tails-1.12-1.10.0.jar                                    | None                                     |
	| LCHIJA | tinkersarsenal                       | 0.5                    | tinkersarsenal-0.5.jar                                   | None                                     |
	| LCHIJA | tipthescales                         | 1.0.3                  | TipTheScales-1.12.2-1.0.3.jar                            | None                                     |
	| LCHIJA | unhealthydying                       | 1.2.2.1                | Unhealthy-Dying-1.2.2.1.jar                              | None                                     |
	| LCHIJA | vampire                              | 0.0.2B                 | vampire-0.0.2B.jar                                       | None                                     |
	| LCHIJA | vampirism                            | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJA | teamlapen-lib                        | 1.4.9                  | Vampirism-1.12.2-1.4.9.jar                               | None                                     |
	| LCHIJA | vampirism_integrations               | vampirism_integrations | VampirismIntegrations-1.12.2-1.1.0-alpha+12-09-22-44.jar | None                                     |
	| LCHIJA | walljump                             | 1.12.2-1.2.1           | walljump-1.12.2-1.2.1.jar                                | None                                     |
	| LCHIJA | passableleaves                       | 2.0.0                  | PassableLeaves-1.12.2-2.0.0.jar                          | None                                     |

	Loaded coremods (and transformers): 
PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  teamrtg.passableleaves.asm.PassableLeavesTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.4.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.07' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2784
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.07, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz

**Comment by Foghrye4** [comment]
This one is harder to check, but I hope a measures I made will prevent it from happening again.
https://minecraft.curseforge.com/projects/iblis/files/2669818
So I won't close this issue for now. Please report if bug is fixed.

**Comment by Foghrye4** [comment]
Proved to be fixed.
