### ISSUE TITLE
Feature/compatibility request

### ISSUE THREAD

**Issue by Josral** [Foghrye4/Iblis#24]
You have 'Level Up' mod advertised on your page.  I am using that mod too.  In that mod when you achieve 5 levels of xp you can choose a path(combat, crafting, mining) to achieve additional xp.  When I choose the crafting path a situation comes up with 'Iblis' practice crafting.  Currently 'Iblis' practice crafting does not give or hook into the 'crafting' xp given by the 'Level Up' mod.  Would it be possible for 'Iblis' to detect that the 'crafting path' has been chosen and somehow allow xp to be gotten from the 'Level Up' mod when 'practice crafting'?

**Comment by Foghrye4** [comment]
I'll see what I can (or cannot) do.

**Comment by Foghrye4** [comment]
Done. Now 'practice crafting' will have effect on crafting XP.
