### ISSUE TITLE
Block Lag when mining blocks and digging

### ISSUE THREAD

**Issue by DatrixTHLK** [Foghrye4/Iblis#26]
Hi, 
Somehow the diamond shovel I use to dig dirt blocks/grass blocks has gotten to the point where minecraft sometimes doesn't notice I dug those blocks (the speed of the digging is what is causing the issue). When broken the blocks become invisible and I sometimes damage myself on them. Is there a way we can get a config option with the max speed we can have on an item and control that? I feel this is better than just disabling the certain skill areas.

Minecraft: 1.12.2
Forge: 14.23.5.2836
Iblis: 0.5.11

**Comment by DatrixTHLK** [comment]
Still happening with 0.5.12.

**Comment by Foghrye4** [comment]
During such occasions type command `/forge tps` and post results here.

**Comment by DatrixTHLK** [comment]
http://i67.tinypic.com/2rh5l41.png

**Comment by Foghrye4** [comment]
I think I've found a source of a bug. Try version  0.5.13

**Comment by DatrixTHLK** [comment]
It's improved a lot since the last version, though there still seems to be some block lag or invisible block. http://i67.tinypic.com/2sblhea.png

**Comment by Foghrye4** [comment]
I have no more ideas. In that case - just disable digging skill. Set `B:digging=false` in `iblis.cfg`

**Comment by DatrixTHLK** [comment]
ok...thanks for the response in any case. I'll just close this then.

Edit: If you have no more ideas, then couldn't the problem be on Forge's side or Minecraft's side? I'm not about to open a bug report for forge anyways because of how I was treated last time I asked a question, and 1.12.2 is no longer being worked on by Mojang, so the question raised is moot at this point.

**Comment by Foghrye4** [comment]
If disabling Digging skill works for you - this is only Iblis problem.
