### ISSUE TITLE
Crash on loading the game

### ISSUE THREAD

**Issue by SirAron111** [Foghrye4/Iblis#33]
https://paste.dimdev.org/hiramuqibu.mccrash ok I get this crash every time I load up since adding iblis. Do I do something wrong? I wanted to check out the skill system of this mod since the improvable skills 3 I am using always resets the skills on death or crash.

**Comment by Foghrye4** [comment]
Recent build of Iblis has updated Electroblob Wizardy API. Try to update Electroblob Wizardy.
