### ISSUE TITLE
Ilbis Gui Buttons

### ISSUE THREAD

**Issue by mmmilord** [Foghrye4/Iblis#35]
Posted this on CF comments, but not sure if it'll get looked at there. with the recipe book removed (FastWorkBench or No Recipe Book), your ui elements get pushed over and cover quark's "Deposit to nearby chests" button.
 
![2019-09-28_03 17 08](https://user-images.githubusercontent.com/45900271/65934917-0ae60580-e40f-11e9-92e4-a5d7feedfb9b.png)

**Comment by Foghrye4** [comment]
Yes, I saw your comment on CurseForge. I just don't think I can fix that.

**Comment by mmmilord** [comment]
No problem, sorry for bothering you!

**Comment by AllieWade** [comment]
@mmmilord , the good news is you *can* move Quark's buttons. You can even do so with the in-game config (esc > q button), so you can tweak the numbers, check the placement, and tweak them again without restarting the client. I personally have the sort button at -20,-22 and the store to chests button at 0,-22, which puts the buttons just above the crafting output and doesn't conflict with anything in my setup; your mileage may, of course, vary.

**Comment by Foghrye4** [comment]
Hmm, I never thought about such solution. Configurable iblis button positions could solve this issue as well.

**Comment by mmmilord** [comment]
> 
> 
> @mmmilord , the good news is you _can_ move Quark's buttons. You can even do so with the in-game config (esc > q button), so you can tweak the numbers, check the placement, and tweak them again without restarting the client. I personally have the sort button at -20,-22 and the store to chests button at 0,-22, which puts the buttons just above the crafting output and doesn't conflict with anything in my setup; your mileage may, of course, vary.

Omg, thank you so much Allie <3 I didn't even know that was possible, I'll give it a go!

**Comment by AllieWade** [comment]
Happy to help. :)
