### ISSUE TITLE
Compatibility request for 'Pickletweaks'

### ISSUE THREAD

**Issue by Josral** [Foghrye4/Iblis#36]
I found a new mod to play with.  'Pickletweaks' [https://www.curseforge.com/minecraft/mc-mods/pickle-tweaks](url) The tools and weapons provided in the mod are compatible with 'Iblis'.  However the 'Pickletweaks' mod allows weapon/tool/armor repair to be done in the crafting grid as opposed to the anvil.  Damaged iron tool plus an iron ingot or two = repaired tool, etc.  It also provides the ability to make repair kits to use.  Question is, should I get weaponsmithing and armorsmithing xp when repairing items as opposed to making new ones.  Would you be interested in adding that compatibility?

**Comment by Foghrye4** [comment]
That sucks, but I can't catch this:
https://github.com/BlakeBr0/PickleTweaks/blob/master/src/main/java/com/blakebr0/pickletweaks/registry/ModRecipes.java#L22
For some reason BlakeBr0 register most of recipes normal way, but this one using mod `Init` event.

**Comment by Josral** [comment]
It's not a big deal.  After some more time with his mod, the material cost for repair of most tools is not worth it.  Might as well construct a new one unless it's enchanted.  His paxels are worth the repair cost in materials though.  I found an anvil mod that keeps the repair cost down to 1 xp cost per repair rather than rising for each repair.  That can work for enchanted stuff.
