### ISSUE TITLE
[Suggestion] Manually changing bonuses gained from skills

### ISSUE THREAD

**Issue by bigboipeepee** [Foghrye4/Iblis#37]
I like this mod and especially the skill tree and how you can train different skills, but the bonuses gained from training are too high.So i think that it would be a great idea for you to add configs to allow us to change the different bonuses gained from skills.Cause it ain't fun becoming a god after killing 10 dogs with my bare fists.Well at least for me.

Also thank you for this amazing mod.

**Comment by Foghrye4** [comment]
I made a configurable skill XP from action instead - much easier for me.
