### ISSUE TITLE
Compatibility Request

### ISSUE THREAD

**Issue by theshadowake** [Foghrye4/Iblis#8]
Would it be possible to make your mod compatible with Apple Core (and by extension Spice of Life and Spice of Life: Carrot Edition)? At the moment it crashes to desktop on loading world if Apple Core is present.

**Comment by Foghrye4** [comment]
I can. It will take some time.

**Comment by theshadowake** [comment]
Thanks appreciate you looking into it 👍

**Comment by Foghrye4** [comment]
Done. Now you should be able to run 0.3.40 of Iblis together with AppleCore.

**Comment by theshadowake** [comment]
Wow, that was fast, legend, thanks 👍
