### ISSUE TITLE
Server Issue with Iblis 0.4.0

### ISSUE THREAD

**Issue by RandomGuyJunior** [Foghrye4/Iblis#9]
After testing my 1.12.2 Server with the newest iblis version it crashes and i get this exception  
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/color/IBlockColor
Isnt that for the Client ? Why is your mod telling my Server to load it ?
Here the full list of my mods on my Server for replication:
-astralsorcery 1.9.4
-Baubles 1.5.2
-CustomStartingGear 1.2.0.9
-dissolution 0.6.1
-Doggy Talents 1.14.2.321
-EpicSiegeMod 13.162
-FastLeafDecay v14
-Forgelin 1.7.4
-howlingmoon 0.9
-iblis 0.4.0
-InfernalMobs 1.12.2
-IronBackpacks 3.0.8-12
-journeymap 5.5.2
-JRFTL 1.1
-LibEx 1.0.8
-librarianlib 4.12
-lostcities 2.0.10
-NetherEx 2.0.8
-Reskillable 1.9.3
-ScalingHealth 1.3.26-127
-SereneSeasons 1.2.6
-SilentLib 3.0.1-145
-SimpleIrontoSteel 1.1
-stg 1.2.3
-TickDynamic 1.0.1
-trumpetskeleton 1.0.2.1
-Vampirism 1.4.5
-Waddles 0.6.0
-wizardry 0.9.6

Crash report:
[crash-2018-08-29_09.21.52-server.txt](https://github.com/Foghrye4/Iblis/files/2332302/crash-2018-08-29_09.21.52-server.txt)
Complete Console Output from startup
https://pastebin.com/EG4GHgqk

**Comment by Foghrye4** [comment]
Thank you! Fixed.

**Comment by RandomGuyJunior** [comment]
Thank you for that!
